const $=id=>document.getElementById(id);
let selected='falcon', totalGold=0,totalRp=0;
const asset = p => `./${p}`;
const aircraft = {
  falcon: {name:'PK-A01 FALCON', role:'Balance Assault', levels:[1,2,3,4,5].map(i=>asset(`assets/aircraft/falcon/falcon_lv${i}.svg`))},
  vulcan: {name:'PK-B01 VULCAN', role:'Heavy Assault', levels:[1,2,3,4,5].map(i=>asset(`assets/aircraft/vulcan/vulcan_lv${i}.svg`))}
};
const enemyAssets={
  scout:asset('assets/enemy/scout/scout_01.svg'),
  interceptor:asset('assets/enemy/interceptor/interceptor_01.svg'),
  bomber:asset('assets/enemy/bomber/bomber_01.svg'),
  elite:asset('assets/enemy/elite/elite_01.svg')
};
const imgs={};
async function loadImage(src){return new Promise((res)=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>res(null);im.src=src;});}
async function preload(){
  const list=[...aircraft.falcon.levels,...aircraft.vulcan.levels,...Object.values(enemyAssets),
    asset('assets/effects/explosions/explosion_s.svg'),asset('assets/effects/shields/shield_hex.svg')];
  for(const src of list) imgs[src]=await loadImage(src);
}
function renderBase(){
  $('shipSvg').innerHTML=`<img src="${aircraft[selected].levels[4]}" style="width:100%;height:100%;object-fit:contain">`;
  $('shipName').innerHTML=`${aircraft[selected].name}<div class="role">${aircraft[selected].role} / SVG Asset Build</div>`;
  $('shipTag').innerHTML=selected==='falcon'?'LV5 SVG<br>FALCON':'LV5 SVG<br>VULCAN';
}
let canvas,ctx,W,H,run=false,paused=false,last=0,speed=1,player,bullets=[],enemies=[],enemyBullets=[],particles=[],stage=1,wave=1,kills=0,goal=24,exp=0,expNeed=50,levelPoints=0,boss=null,weapons={straight:1,laser:0,chain:0,shield:0,wingS:0,wingH:0};
function resize(){W=canvas.width=innerWidth;H=canvas.height=innerHeight}
function start(){resize();run=true;paused=false;last=performance.now();player={x:W/2,y:H-95,hp:100,maxHp:100,lv:1,fire:0,wing:0,homing:0};bullets=[];enemies=[];enemyBullets=[];particles=[];stage=1;wave=1;kills=0;goal=24;exp=0;levelPoints=0;boss=null;weapons={straight:1,laser:0,chain:0,shield:0,wingS:0,wingH:0};msg('LAUNCH');requestAnimationFrame(loop)}
let drag=false;function pointer(e){const r=canvas.getBoundingClientRect();player.x=e.clientX-r.left;player.y=e.clientY-r.top-35}
function loop(t){if(!run)return;const dt=Math.min((t-last)/1000,.033);last=t;if(!paused){update(dt*speed);draw()}requestAnimationFrame(loop)}
function update(dt){player.fire-=dt;player.wing-=dt;player.homing-=dt;if(player.fire<=0){fire();player.fire=.16}if(weapons.wingS>0&&player.wing<=0){fireWingS();player.wing=Math.max(.28,.75-weapons.wingS*.08)}if(weapons.wingH>0&&player.homing<=0){fireWingH();player.homing=Math.max(.42,1.05-weapons.wingH*.1)}if(!boss&&Math.random()<dt*(1.1+stage*.08+wave*.12))spawnEnemy();enemies.forEach(e=>{e.y+=e.v*dt;if(e.shoot){e.cool-=dt;if(e.cool<=0){e.cool=1.2;enemyBullets.push({x:e.x,y:e.y,vx:0,vy:170,life:3})}}});if(boss){boss.cool-=dt;if(boss.cool<=0){boss.cool=.6;for(let i=-2;i<=2;i++)enemyBullets.push({x:boss.x,y:boss.y+50,vx:i*65,vy:185,life:3})}}bullets.forEach(b=>{if(b.type==='homing'){let target=nearest(b.x,b.y);if(target){let dx=target.x-b.x,dy=target.y-b.y,l=Math.hypot(dx,dy)||1;b.vx+=(dx/l)*500*dt;b.vy+=(dy/l)*500*dt;let s=Math.hypot(b.vx,b.vy)||1;b.vx=b.vx/s*380;b.vy=b.vy/s*380}}b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt});enemyBullets.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.r+=dt*20});bullets=bullets.filter(b=>b.life>0&&b.y>-100&&b.y<H+100);enemyBullets=enemyBullets.filter(b=>b.life>0&&b.y<H+100);particles=particles.filter(p=>p.life>0);collide();enemies=enemies.filter(e=>e.hp>0&&e.y<H+80);if(player.hp<=0)endRun('GAME OVER');ui()}
function fire(){const count=[1,2,4,5,7][weapons.straight-1];const pattern=[0,-8,8,-15,15,-28,28].slice(0,count);pattern.forEach(a=>{let r=a*Math.PI/180;bullets.push({x:player.x,y:player.y-36,vx:Math.sin(r)*280,vy:-540*Math.cos(r),dmg:12+stage,life:2,type:'straight'})});if(weapons.laser>0)bullets.push({x:player.x,y:player.y-250,vx:0,vy:0,dmg:2+weapons.laser,life:.12,type:'laser',w:12+weapons.laser*5,h:430})}
function fireWingS(){(weapons.wingS>=2?[[-58,24],[58,24]]:[[-58,24]]).forEach(p=>bullets.push({x:player.x+p[0],y:player.y+p[1]-40,vx:0,vy:-450,dmg:8+weapons.wingS*3,life:2,type:'wing'}))}
function fireWingH(){(weapons.wingH>=2?[[-72,42],[72,42]]:[[72,42]]).forEach(p=>bullets.push({x:player.x+p[0],y:player.y+p[1]-40,vx:0,vy:-360,dmg:9+weapons.wingH*3,life:3,type:'homing'}))}
function spawnEnemy(){let pool=wave>=3?['scout','interceptor','bomber','elite']:wave>=2?['scout','interceptor','bomber']:['scout','scout','interceptor'];let type=pool[Math.floor(Math.random()*pool.length)];let hp=type==='elite'?150:type==='bomber'?65:type==='interceptor'?22:28;enemies.push({type,x:30+Math.random()*(W-60),y:-45,hp,maxHp:hp,v:type==='interceptor'?175:type==='bomber'?52:type==='elite'?58:88,shoot:type==='bomber'||type==='elite',cool:1})}
function spawnBoss(){boss={x:W/2,y:120,hp:1800+stage*150,maxHp:1800+stage*150,cool:.5};msg('WARNING<br>BOSS',true)}
function nearest(x,y){let arr=boss?[...enemies,boss]:enemies,best=null,bd=99999;arr.forEach(e=>{let d=Math.hypot(e.x-x,e.y-y);if(d<bd){bd=d;best=e}});return best}
function boom(x,y,big=false){for(let i=0;i<(big?22:9);i++){let a=Math.random()*6.28,s=(big?100:60)+Math.random()*80;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:big?.9:.45,r:3,color:Math.random()>.5?'#f6d35c':'#fb923c'})}}
function collide(){bullets.forEach(b=>{if(b.type==='laser'){enemies.forEach(e=>{if(Math.abs(e.x-b.x)<b.w+25&&e.y>b.y-b.h/2&&e.y<b.y+b.h/2)e.hp-=b.dmg});if(boss&&Math.abs(boss.x-b.x)<100)boss.hp-=b.dmg;return}enemies.forEach(e=>{if(Math.hypot(e.x-b.x,e.y-b.y)<28){e.hp-=b.dmg;b.life=0;particles.push({x:e.x,y:e.y,vx:0,vy:-20,life:.18,r:4,color:'#f6d35c'});if(weapons.chain>0)enemies.forEach(o=>{if(o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<100+weapons.chain*20)o.hp-=5+weapons.chain*3})}});if(boss&&Math.hypot(boss.x-b.x,boss.y-b.y)<105){boss.hp-=b.dmg;b.life=0}});enemies.forEach(e=>{if(e.hp<=0&&!e.dead){e.dead=true;kills++;exp+=e.type==='elite'?25:9;totalGold+=e.type==='elite'?10:2;boom(e.x,e.y,e.type==='elite');if(kills>=goal&&!boss){if(wave<3){wave++;kills=0;goal+=8;msg('WAVE '+wave)}else if(stage%5===0)spawnBoss();else nextStage()}}});if(boss&&boss.hp<=0){totalGold+=50;totalRp+=5;boom(boss.x,boss.y,true);boss=null;nextStage();msg('BOSS CLEAR')}enemyBullets.forEach(p=>{if(Math.hypot(p.x-player.x,p.y-player.y)<20){player.hp-=Math.max(2,10-weapons.shield*2);p.life=0}});while(exp>=expNeed){exp-=expNeed;expNeed=Math.floor(expNeed*1.35+22);levelPoints++;$('levelBtn').style.display='flex';$('levelCount').textContent=levelPoints}}
function nextStage(){stage++;wave=1;kills=0;goal=24+stage*5;msg('STAGE '+stage);if(stage%5===0)setTimeout(spawnBoss,700)}
function msg(t,w=false){$('centerMsg').innerHTML=t;$('centerMsg').className=w?'msg warning':'msg';$('centerMsg').style.display='block';setTimeout(()=>$('centerMsg').style.display='none',1150)}
function openLevel(){if(levelPoints<=0)return;$('levelModal').style.display='flex';const opts=[['Straight +1','정면 화력','straight'],['Laser +1','관통 레이저','laser'],['Chain +1','연쇄 피해','chain'],['Shield +1','육각 실드','shield'],['Wing S +1','정면 보조기','wingS'],['Wing H +1','유도 보조기','wingH']].sort(()=>Math.random()-.5).slice(0,3);$('cards').innerHTML=opts.map((o,i)=>`<div class="card ${i===0?'gold':''}" data-w="${o[2]}"><h3>${o[0]}</h3><p>${o[1]}</p></div>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{weapons[c.dataset.w]=Math.min(5,(weapons[c.dataset.w]||0)+1);if(c.dataset.w==='straight')player.lv=Math.min(5,weapons.straight);levelPoints--;$('levelModal').style.display='none';$('levelCount').textContent=levelPoints;if(levelPoints<=0)$('levelBtn').style.display='none'})}
function endRun(title){if(!run)return;run=false;paused=true;$('resultTitle').textContent=title;$('resultText').innerHTML=`Stage ${stage} / Wave ${wave}<br>Gold ${totalGold}<br>RP ${totalRp}`;$('resultModal').style.display='flex';$('goldTop').textContent='GOLD '+totalGold;$('rpTop').textContent='RP '+totalRp}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#071127';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(56,189,248,.07)';for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y+(performance.now()/42%40));ctx.lineTo(W,y+(performance.now()/42%40));ctx.stroke()}bullets.forEach(b=>{if(b.type==='laser'){ctx.fillStyle='rgba(56,189,248,.22)';ctx.fillRect(b.x-b.w/2,b.y-b.h/2,b.w,b.h);ctx.fillStyle='#fff';ctx.fillRect(b.x-2,b.y-b.h/2,4,b.h)}else{ctx.fillStyle=b.type==='homing'?'#38bdf8':b.type==='wing'?'#f6d35c':'#fde68a';ctx.beginPath();ctx.arc(b.x,b.y,b.type==='homing'?5:4,0,6.28);ctx.fill()}});enemies.forEach(e=>{let im=imgs[enemyAssets[e.type]];if(im)ctx.drawImage(im,e.x-34,e.y-34,68,68)});if(boss){let im=imgs[asset('assets/enemy/boss/boss_stage5.svg')];if(im)ctx.drawImage(im,boss.x-95,boss.y-95,190,190);ctx.fillStyle='#f6d35c';ctx.fillRect(30,62,(W-60)*boss.hp/boss.maxHp,12);ctx.strokeStyle='#fff';ctx.strokeRect(30,62,W-60,12)}enemyBullets.forEach(p=>{ctx.fillStyle='#fb923c';ctx.beginPath();ctx.arc(p.x,p.y,6,0,6.28);ctx.fill()});particles.forEach(p=>{ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(p.life,0);ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,6.28);ctx.fill();ctx.globalAlpha=1});drawWingmen();let im=imgs[aircraft[selected].levels[Math.max(0,player.lv-1)]];if(im)ctx.drawImage(im,player.x-56,player.y-56,112,112);if(weapons.shield>0){ctx.strokeStyle='rgba(56,189,248,.58)';ctx.lineWidth=3;ctx.beginPath();let r=45+weapons.shield*8;for(let i=0;i<6;i++){let a=Math.PI/3*i+Math.PI/6,x=player.x+Math.cos(a)*r,y=player.y+Math.sin(a)*r;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();ctx.stroke()}}
function drawWingmen(){function d(x,y,t){ctx.fillStyle=t==='h'?'#38bdf8':'#f6d35c';ctx.strokeStyle='#0f172a';ctx.beginPath();ctx.moveTo(x,y-20);ctx.lineTo(x-13,y+15);ctx.lineTo(x,y+8);ctx.lineTo(x+13,y+15);ctx.closePath();ctx.fill();ctx.stroke()}if(weapons.wingS>0)(weapons.wingS>=2?[[-58,24],[58,24]]:[[-58,24]]).forEach(p=>d(player.x+p[0],player.y+p[1],'s'));if(weapons.wingH>0)(weapons.wingH>=2?[[-72,42],[72,42]]:[[72,42]]).forEach(p=>d(player.x+p[0],player.y+p[1],'h'))}
function ui(){$('stageText').textContent='STAGE '+stage+(boss?' / BOSS':'');$('killText').textContent=boss?'BOSS HP':`WAVE ${wave} / KILL ${Math.min(kills,goal)}/${goal}`;$('stageFill').style.width=(Math.min(kills/goal,1)*100)+'%';$('hpFill').style.width=Math.max(player.hp/player.maxHp*100,0)+'%';$('expFill').style.width=Math.min(exp/expNeed*100,100)+'%';$('weaponText').innerHTML=`Straight Lv${weapons.straight}<br>Laser Lv${weapons.laser}<br>Chain Lv${weapons.chain}<br>Shield Lv${weapons.shield}<br>Wing S Lv${weapons.wingS}<br>Wing H Lv${weapons.wingH}`;$('bossBar').style.display=boss?'block':'none';if(boss)$('bossFill').style.width=(boss.hp/boss.maxHp*100)+'%'}
window.addEventListener('load',async()=>{canvas=$('gameCanvas');ctx=canvas.getContext('2d');await preload();renderBase();$('aircraftBtn').onclick=()=>{selected=selected==='falcon'?'vulcan':'falcon';renderBase()};$('startBtn').onclick=()=>{$('base').classList.remove('active');$('game').classList.add('active');setTimeout(start,60)};$('pauseBtn').onclick=()=>{paused=true;$('pauseModal').style.display='flex'};$('continueBtn').onclick=()=>{paused=false;$('pauseModal').style.display='none'};$('settleBtn').onclick=()=>{$('pauseModal').style.display='none';endRun('정산')};$('backBaseBtn').onclick=()=>{$('resultModal').style.display='none';$('game').classList.remove('active');$('base').classList.add('active')};$('speedBtn').onclick=()=>{speed=speed>=5?1:speed+1;$('speedBtn').innerHTML='⏩<br>x'+speed};$('levelBtn').onclick=openLevel;canvas.addEventListener('pointerdown',e=>{drag=true;pointer(e)});canvas.addEventListener('pointermove',e=>{if(drag)pointer(e)});addEventListener('pointerup',()=>drag=false);addEventListener('resize',resize)});
window.toast=(t)=>{let b=$('toastBox');b.textContent=t;b.style.display='block';setTimeout(()=>b.style.display='none',1300)}
